version: "3.7"

services:
  app:
    build:
      context: .
      args:
        - user=${APP_USER}
        - uid=${APP_UID}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${APP_PATH}:/var/www
    networks:
      - design-patterns-creation

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ${APP_PATH}:/var/www
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/
    networks:
      - design-patterns-creation

networks:
  design-patterns-creation:
    driver: bridge
